#include <ansi.h>
inherit SKILL;
mapping *quest = ({
        ([      "quest":                "æﬁ–Õ»Æ",
                "quest_type":           "…±",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "¡ı¿œ≈©",
                "quest_type":           "…±",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "ƒ¡—Ú≈Æ",
                "quest_type":           "…±",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "ƒ¡—Ú±ﬁ",
                "quest_type":           "—∞",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "—Ú√´»π",
                "quest_type":           "—∞",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "ª®¥Ûπ√",
                "quest_type":           "…±",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "≤®Àπ≈´",
                "quest_type":           "…±",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "Õ‰µ∂",
                "quest_type":           "—∞",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "ª§…Ω π’ﬂ",
                "quest_type":           "…±",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "Ã“ƒæΩ£",
                "quest_type":           "—∞",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "¥Û∫∫",
                "quest_type":           "…±",
                "exp_bonus":            50,
        ]),
        ([      "quest":                " ˜÷¶",
                "quest_type":           "—∞",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "Œ‰¡÷¥Û∫¿Ω‹",
                "quest_type":           "…±",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "Ã˙ª§Œ¿",
                "quest_type":           "…±",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "Õ≠ª§Œ¿",
                "quest_type":           "…±",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "µ•…ÌÃÀ◊” ÷",
                "quest_type":           "…±",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "Ô⁄ ¶",
                "quest_type":           "…±",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "ÃÀ◊” ÷",
                "quest_type":           "…±",
                "exp_bonus":            50,
        ]),
        ([      "quest":                " ØÀ¯",
                "quest_type":           "—∞",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "–°—æª∑",
                "quest_type":           "…±",
                "exp_bonus":            50,
        ]),
        ([      "quest":               HIG "«≥¬Ã–°π”" NOR,
                "quest_type":           "—∞",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "π˘·‘—Ù",
                "quest_type":           "…±",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "–°ª®»π",
                "quest_type":           "—∞",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "œ„¡‚",
                "quest_type":           "…±",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "÷Ó∏¿◊",
                "quest_type":           "…±",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "∑Á¡Ë",
                "quest_type":           "…±",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "≈÷ÊŒøÕ",
                "quest_type":           "…±",
                "exp_bonus":            50,
        ]),
        ([      "quest":                " ›ÊŒøÕ",
                "quest_type":           "…±",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "∫˛…œ≤›",
                "quest_type":           "…±",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "≤›…¿",
                "quest_type":           "—∞",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "∫˛…œª®",
                "quest_type":           "…±",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "ª®…¿",
                "quest_type":           "—∞",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "¡÷œ…∂˘",
                "quest_type":           "…±",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "“¯∫Ï…¢ª®»π",
                "quest_type":           "—∞",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "∫˛…œæ∆",
                "quest_type":           "…±",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "æ∆…¿",
                "quest_type":           "—∞",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "∫˛…œ¡¯",
                "quest_type":           "…±",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "¡¯…¿",
                "quest_type":           "—∞",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "∫Ï≥ÒŒË∆˜",
                "quest_type":           "—∞",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "∫˛…œ≈Æ",
                "quest_type":           "…±",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "≈Æ…¿",
                "quest_type":           "—∞",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "∫˛…œÀÆ",
                "quest_type":           "…±",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "ÀÆ…¿",
                "quest_type":           "—∞",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "ÀÆ”ÒËµ",
                "quest_type":           "—∞",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "∫˛…œ—©",
                "quest_type":           "…±",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "—©…¿",
                "quest_type":           "—∞",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "∫˛…œ‘¬",
                "quest_type":           "…±",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "‘¬…¿",
                "quest_type":           "—∞",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "¥‰”Ò≈˝≈√",
                "quest_type":           "—∞",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "¥Û’‰÷È",
                "quest_type":           "—∞",
                "exp_bonus":            50,
        ]),

});
mapping query_quest()
{
        return quest[random(sizeof(quest))];
}

